### ISSUE TITLE
round_rsi argument in Stochastic_RSI

### ISSUE THREAD

**Issue by vkorobeynyk** [lukaszbinden/rsi_tradingview#4]
Hello,

Thanks a lot for creating this, I spend so much time trying to understand the tradingview code...
RSI works wonderfully but for the stochastic it gives an error regarding the round_rsi argument when you invoke:

`# Calculate RSI
    rsi = rsi_tradingview(ohlc, period=period, round_rsi=False)`

Its not defined in the rsi_tradingview and if I take it away I get error

` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: window must be an integer ` 

which I assume comes from .rolling function because it wants integers as input...

Unfortunately I am not very proficient in python, as I call your python scripts from R. Do you know a turn around to this issue?

**Comment by lukaszbinden** [comment]
Hi,

thanks for pointing that out. Indeed, I forgot to add this parameter. It's fixed now.

Cheers, 
Lukas

**Comment by vkorobeynyk** [comment]
Thanks for fixing that. Unfortunately I still get the error 

`Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: window must be an integer`
 when I run stoch_rsi_tradingview.

Is that error because the rsi values are not integers?

**Comment by lukaszbinden** [comment]
the code runs fine, check the test.py...
